export interface ObjectDetectionClass {
  name: string;
  value: string;
  id: number;
  category: string;
  visible: boolean;
  displayName: string;
}

export const COCO_SSD_CLASSES: ObjectDetectionClass[] = [
  {
    id: 1,
    value: '/m/01g317',
    name: 'person',
    displayName: 'Persona',
    category: 'Seres vivos',
    visible: false,
  },
  {
    id: 2,
    value: '/m/0199g',
    name: 'bicycle',
    category: 'Medios de transporte',
    displayName: 'Bicicleta',
    visible: true,
  },
  {
    id: 3,
    value: '/m/0k4j',
    name: 'car',
    displayName: 'Automóvil',
    category: 'Medios de transporte',
    visible: true,
  },
  {
    id: 4,
    value: '/m/04_sv',
    name: 'motorcycle',
    displayName: 'Motocicleta',
    category: 'Medios de transporte',
    visible: false,
  },
  {
    id: 5,
    value: '/m/05czz6l',
    name: 'airplane',
    displayName: 'Avión',
    category: 'Medios de transporte',
    visible: true,
  },
  {
    id: 6,
    value: '/m/01bjv',
    name: 'bus',
    displayName: 'Autobus',
    category: 'Medios de transporte',
    visible: true,
  },
  {
    id: 7,
    value: '/m/07jdr',
    name: 'train',
    displayName: 'Tren',
    category: 'Medios de transporte',
    visible: true,
  },
  {
    id: 8,
    value: '/m/07r04',
    name: 'truck',
    displayName: 'Camión',
    category: 'Medios de transporte',
    visible: true,
  },
  {
    id: 9,
    value: '/m/019jd',
    name: 'boat',
    displayName: 'Barco',
    category: 'Medios de transporte',
    visible: true,
  },
  {
    id: 10,
    value: '/m/015qff',
    name: 'traffic light',
    displayName: 'Luz de tráfico',
    category: 'En la calle',
    visible: true,
  },
  {
    id: 11,
    value: '/m/01pns0',
    name: 'fire hydrant',
    displayName: 'Hidrante',
    category: 'En la calle',
    visible: true,
  },
  {
    id: 13,
    value: '/m/02pv19',
    name: 'stop sign',
    category: 'En la calle',
    displayName: 'Señal de alto',
    visible: true,
  },
  {
    id: 14,
    value: '/m/015qbp',
    name: 'parking meter',
    category: 'En la calle',
    displayName: 'Parquímetro',
    visible: true,
  },
  {
    id: 15,
    value: '/m/0cvnqh',
    name: 'bench',
    category: 'En la calle',
    displayName: 'Asiento',
    visible: true,
  },
  {
    id: 16,
    value: '/m/015p6',
    name: 'bird',
    category: 'Seres vivos',
    displayName: 'Pajaro',
    visible: true,
  },
  {
    id: 17,
    value: '/m/01yrx',
    name: 'cat',
    category: 'Seres vivos',
    displayName: 'Gato',
    visible: true,
  },
  {
    id: 18,
    value: '/m/0bt9lr',
    name: 'dog',
    category: 'Seres vivos',
    displayName: 'Perro',
    visible: true,
  },
  {
    id: 19,
    value: '/m/03k3r',
    name: 'horse',
    category: 'Seres vivos',
    displayName: 'Caballo',
    visible: true,
  },
  {
    id: 20,
    value: '/m/07bgp',
    name: 'sheep',
    category: 'Seres vivos',
    displayName: 'Oveja',
    visible: true,
  },
  {
    id: 21,
    value: '/m/01xq0k1',
    name: 'cow',
    displayName: 'Vaca',
    category: 'Seres vivos',
    visible: true,
  },
  {
    id: 22,
    value: '/m/0bwd_0j',
    name: 'elephant',
    category: 'Seres vivos',
    displayName: 'Elefante',
    visible: true,
  },
  {
    id: 23,
    value: '/m/01dws',
    name: 'bear',
    category: 'Seres vivos',
    displayName: 'Oso',
    visible: false,
  },
  {
    id: 24,
    value: '/m/0898b',
    name: 'zebra',
    category: 'Seres vivos',
    displayName: 'Zebra',
    visible: false,
  },
  {
    id: 25,
    value: '/m/03bk1',
    name: 'giraffe',
    category: 'Seres vivos',
    displayName: 'Girafa',
    visible: false,
  },
  {
    id: 27,
    value: '/m/01940j',
    name: 'backpack',
    displayName: 'Mochila',
    category: 'Objetos movibles',
    visible: false,
  },
  {
    id: 28,
    value: '/m/0hnnb',
    name: 'umbrella',
    displayName: 'Sombrilla',
    category: 'Objetos movibles',
    visible: false,
  },
  {
    id: 31,
    value: '/m/080hkjn',
    name: 'handbag',
    displayName: 'Bolso',
    category: 'Objetos movibles',
    visible: false,
  },
  {
    id: 32,
    value: '/m/01rkbr',
    name: 'tie',
    displayName: 'Corbata',
    category: 'Objetos movibles',
    visible: false,
  },
  {
    id: 33,
    value: '/m/01s55n',
    name: 'suitcase',
    displayName: 'Maleta',
    category: 'Objetos movibles',
    visible: false,
  },
  {
    id: 34,
    value: '/m/02wmf',
    name: 'frisbee',
    displayName: 'Frisbee',
    category: 'Deportes',
    visible: false,
  },
  {
    id: 35,
    value: '/m/071p9',
    name: 'skis',
    displayName: 'Esquís',
    category: 'Deportes',
    visible: false,
  },
  {
    id: 36,
    value: '/m/06__v',
    name: 'snowboard',
    category: 'Deportes',
    displayName: 'Tabla de snowboard',
    visible: false,
  },
  {
    id: 37,
    value: '/m/018xm',
    name: 'sports ball',
    displayName: 'Pelota',
    category: 'Deportes',
    visible: true,
  },
  {
    id: 38,
    value: '/m/02zt3',
    name: 'kite',
    displayName: 'Cometa',
    category: 'Deportes',
    visible: true,
  },
  {
    id: 39,
    value: '/m/03g8mr',
    name: 'baseball bat',
    category: 'Deportes',
    displayName: 'Bate de béisbol',
    visible: false,
  },
  {
    id: 40,
    value: '/m/03grzl',
    name: 'baseball glove',
    category: 'Deportes',
    displayName: 'Guante de béisbol',
    visible: false,
  },
  {
    id: 41,
    value: '/m/06_fw',
    name: 'skateboard',
    category: 'Deportes',
    displayName: 'Patineta',
    visible: false,
  },
  {
    id: 42,
    value: '/m/019w40',
    name: 'surfboard',
    category: 'Deportes',
    displayName: 'Tabla de surf',
    visible: false,
  },
  {
    id: 43,
    value: '/m/0dv9c',
    name: 'tennis racket',
    category: 'Deportes',
    displayName: 'Raqueta de tenis',
    visible: true,
  },
  {
    id: 44,
    value: '/m/04dr76w',
    name: 'bottle',
    category: 'Objetos del hogar',
    displayName: 'Botella',
    visible: true,
  },
  {
    id: 46,
    value: '/m/09tvcd',
    name: 'wine glass',
    category: 'Objetos del hogar',
    displayName: 'Botella de vino',
    visible: true,
  },
  {
    id: 47,
    value: '/m/08gqpm',
    name: 'cup',
    category: 'Objetos del hogar',
    displayName: 'Taza',
    visible: true,
  },
  {
    id: 48,
    value: '/m/0dt3t',
    name: 'fork',
    category: 'Objetos del hogar',
    displayName: 'Tenedor',
    visible: true,
  },
  {
    id: 49,
    value: '/m/04ctx',
    name: 'knife',
    category: 'Objetos del hogar',
    displayName: 'Cuchillo',
    visible: true,
  },
  {
    id: 50,
    value: '/m/0cmx8',
    name: 'spoon',
    category: 'Objetos del hogar',
    displayName: 'Cuachara',
    visible: true,
  },
  {
    id: 51,
    value: '/m/04kkgm',
    name: 'bowl',
    category: 'Objetos del hogar',
    displayName: 'Bol',
    visible: true,
  },
  {
    id: 52,
    value: '/m/09qck',
    name: 'banana',
    category: 'Comida',
    displayName: 'Banana',
    visible: true,
  },
  {
    id: 53,
    value: '/m/014j1m',
    name: 'apple',
    category: 'Comida',
    displayName: 'Manzana',
    visible: true,
  },
  {
    id: 54,
    value: '/m/0l515',
    name: 'sandwich',
    category: 'Comida',
    displayName: 'Sandwich',
    visible: true,
  },
  {
    id: 55,
    value: '/m/0cyhj_',
    name: 'orange',
    category: 'Comida',
    displayName: 'Orange',
    visible: true,
  },
  {
    id: 56,
    value: '/m/0hkxq',
    name: 'broccoli',
    category: 'Comida',
    displayName: 'Brocoli',
    visible: true,
  },
  {
    id: 57,
    value: '/m/0fj52s',
    name: 'carrot',
    category: 'Comida',
    displayName: 'Zanahoria',
    visible: false,
  },
  {
    id: 58,
    value: '/m/01b9xk',
    name: 'hot dog',
    category: 'Comida',
    displayName: 'Salchicha',
    visible: false,
  },
  {
    id: 59,
    value: '/m/0663v',
    name: 'pizza',
    category: 'Comida',
    displayName: 'Pizza',
    visible: false,
  },
  {
    id: 60,
    value: '/m/0jy4k',
    name: 'donut',
    category: 'Comida',
    displayName: 'Dona',
    visible: false,
  },
  {
    id: 61,
    value: '/m/0fszt',
    name: 'cake',
    category: 'Comida',
    displayName: 'Pastel',
    visible: true,
  },
  {
    id: 62,
    value: '/m/01mzpv',
    name: 'chair',
    category: 'Objetos del hogar',
    displayName: 'Silla',
    visible: true,
  },
  {
    id: 63,
    value: '/m/02crq1',
    name: 'couch',
    category: 'Objetos del hogar',
    displayName: 'Sofá',
    visible: true,
  },
  {
    id: 64,
    value: '/m/03fp41',
    name: 'potted plant',
    category: 'Objetos del hogar',
    displayName: 'Planta en maceta',
    visible: true,
  },
  {
    id: 65,
    value: '/m/03ssj5',
    name: 'bed',
    displayName: 'Cama',
    category: 'Objetos del hogar',
    visible: true,
  },
  {
    id: 67,
    value: '/m/04bcr3',
    name: 'dining table',
    category: 'Objetos del hogar',
    displayName: 'Mesa de comedor',
    visible: true,
  },
  {
    id: 70,
    value: '/m/09g1w',
    name: 'toilet',
    category: 'Objetos del hogar',
    displayName: 'Inodoro',
    visible: true,
  },
  {
    id: 72,
    value: '/m/07c52',
    name: 'tv',
    category: 'Electrónica',
    displayName: 'Televisión',
    visible: true,
  },
  {
    id: 73,
    value: '/m/01c648',
    name: 'laptop',
    category: 'Electrónica',
    displayName: 'Computadora portátil',
    visible: true,
  },
  {
    id: 74,
    value: '/m/020lf',
    name: 'mouse',
    category: 'Electrónica',
    displayName: 'Mouse',
    visible: true,
  },
  {
    id: 75,
    value: '/m/0qjjc',
    name: 'remote',
    category: 'Electrónica',
    displayName: 'Control remoto',
    visible: true,
  },
  {
    id: 76,
    value: '/m/01m2v',
    name: 'keyboard',
    displayName: 'Teclado',
    category: 'Electrónica',
    visible: true,
  },
  {
    id: 77,
    value: '/m/050k8',
    name: 'cell phone',
    category: 'Electrónica',
    displayName: 'Celular',
    visible: true,
  },
  {
    id: 78,
    value: '/m/0fx9l',
    name: 'microwave',
    category: 'Objetos del hogar',
    displayName: 'Microondas',
    visible: true,
  },
  {
    id: 79,
    value: '/m/029bxz',
    name: 'oven',
    category: 'Objetos del hogar',
    displayName: 'Horno',
    visible: true,
  },
  {
    id: 80,
    value: '/m/01k6s3',
    name: 'toaster',
    category: 'Objetos del hogar',
    displayName: 'Tostadora',
    visible: true,
  },
  {
    id: 81,
    value: '/m/0130jx',
    name: 'sink',
    category: 'Objetos del hogar',
    displayName: 'Lavabo',
    visible: true,
  },
  {
    id: 82,
    value: '/m/040b_t',
    name: 'refrigerator',
    category: 'Objetos del hogar',
    displayName: 'Heladera',
    visible: true,
  },
  {
    id: 84,
    value: '/m/0bt_c3',
    name: 'book',
    category: 'Objetos del hogar',
    displayName: 'Libro',
    visible: true,
  },
  {
    id: 85,
    value: '/m/01x3z',
    name: 'clock',
    category: 'Objetos del hogar',
    displayName: 'Reloj de pared',
    visible: true,
  },
  {
    id: 86,
    value: '/m/02s195',
    name: 'vase',
    category: 'Objetos del hogar',
    displayName: 'Jarrón',
    visible: false,
  },
  {
    id: 87,
    value: '/m/01lsmm',
    name: 'scissors',
    category: 'Objetos del hogar',
    displayName: 'Tijeras',
    visible: false,
  },
  {
    id: 88,
    value: '/m/0kmg4',
    name: 'teddy bear',
    category: 'Objetos del hogar',
    displayName: 'Oso de peluche',
    visible: false,
  },
  {
    id: 89,
    value: '/m/03wvsk',
    name: 'hair drier',
    category: 'Objetos del hogar',
    displayName: 'Secador de pelo',
    visible: false,
  },
  {
    id: 90,
    value: '/m/012xff',
    name: 'toothbrush',
    category: 'Objetos del hogar',
    displayName: 'Cepillo de dientes',
    visible: false,
  },
];
